% Predicted stress facts: predicted_stress(FacultyID, Stress).
predicted_stress('F001','Medium').
predicted_stress('F002','Medium').
predicted_stress('F003','Low').
predicted_stress('F004','Medium').
predicted_stress('F005','Medium').
predicted_stress('F006','Medium').
predicted_stress('F007','Medium').
predicted_stress('F008','Medium').
predicted_stress('F009','Low').
predicted_stress('F010','Medium').
predicted_stress('F011','Medium').
predicted_stress('F012','Medium').
predicted_stress('F013','Medium').
predicted_stress('F014','Medium').
predicted_stress('F015','Low').
predicted_stress('F016','Medium').
predicted_stress('F017','Low').
predicted_stress('F018','Low').
predicted_stress('F019','Medium').
predicted_stress('F020','Low').
predicted_stress('F021','Medium').
predicted_stress('F022','Medium').
predicted_stress('F023','Medium').
predicted_stress('F024','Medium').
predicted_stress('F025','Medium').
predicted_stress('F026','Medium').
predicted_stress('F027','Medium').
predicted_stress('F028','Medium').
predicted_stress('F029','Low').
predicted_stress('F030','Medium').
predicted_stress('F031','Low').
predicted_stress('F032','Medium').
predicted_stress('F033','Medium').
predicted_stress('F034','Medium').
predicted_stress('F035','Medium').
predicted_stress('F036','Medium').
predicted_stress('F037','Medium').
predicted_stress('F038','Medium').
predicted_stress('F039','Medium').
predicted_stress('F040','Medium').
predicted_stress('F041','Low').
predicted_stress('F042','Low').
predicted_stress('F043','Low').
predicted_stress('F044','Medium').
predicted_stress('F045','Medium').
predicted_stress('F046','Medium').
predicted_stress('F047','Medium').
predicted_stress('F048','Medium').
predicted_stress('F049','Low').
predicted_stress('F050','Medium').
predicted_stress('F051','Medium').
predicted_stress('F052','Low').
predicted_stress('F053','Medium').
predicted_stress('F054','Medium').
predicted_stress('F055','Medium').
predicted_stress('F056','Medium').
predicted_stress('F057','Medium').
predicted_stress('F058','Medium').
predicted_stress('F059','Low').
predicted_stress('F060','Medium').
predicted_stress('F061','Medium').
predicted_stress('F062','Low').
predicted_stress('F063','Low').
predicted_stress('F064','Low').
predicted_stress('F065','Low').
predicted_stress('F066','Medium').
predicted_stress('F067','Medium').
predicted_stress('F068','Medium').
predicted_stress('F069','Medium').
predicted_stress('F070','Medium').
predicted_stress('F071','Medium').
predicted_stress('F072','Medium').
predicted_stress('F073','Medium').
predicted_stress('F074','Medium').
predicted_stress('F075','Low').
predicted_stress('F076','Medium').
predicted_stress('F077','Low').
predicted_stress('F078','Medium').
predicted_stress('F079','Medium').
predicted_stress('F080','Low').
predicted_stress('F081','Medium').
predicted_stress('F082','Medium').
predicted_stress('F083','Medium').
predicted_stress('F084','Medium').
predicted_stress('F085','Medium').
predicted_stress('F086','Low').
predicted_stress('F087','Medium').
predicted_stress('F088','Low').
predicted_stress('F089','Medium').
predicted_stress('F090','Low').
predicted_stress('F091','Low').
predicted_stress('F092','Medium').
predicted_stress('F093','Medium').
predicted_stress('F094','Medium').
predicted_stress('F095','Low').
predicted_stress('F096','Medium').
predicted_stress('F097','Medium').
predicted_stress('F098','Medium').
predicted_stress('F099','Medium').
predicted_stress('F100','Low').
predicted_stress('F101','Low').
predicted_stress('F102','Medium').
predicted_stress('F103','Medium').
predicted_stress('F104','Medium').
predicted_stress('F105','Medium').
predicted_stress('F106','Medium').
predicted_stress('F107','Low').
predicted_stress('F108','Medium').
predicted_stress('F109','Medium').
predicted_stress('F110','Medium').
predicted_stress('F111','Medium').
predicted_stress('F112','Medium').
predicted_stress('F113','Medium').
predicted_stress('F114','Medium').
predicted_stress('F115','Low').
predicted_stress('F116','Medium').
predicted_stress('F117','Medium').
predicted_stress('F118','Medium').
predicted_stress('F119','Low').
predicted_stress('F120','Medium').
predicted_stress('F121','Medium').
predicted_stress('F122','Medium').
predicted_stress('F123','Low').
predicted_stress('F124','Medium').
predicted_stress('F125','Medium').
predicted_stress('F126','Low').
predicted_stress('F127','Low').
predicted_stress('F128','Medium').
predicted_stress('F129','Medium').
predicted_stress('F130','Medium').
predicted_stress('F131','Medium').
predicted_stress('F132','Low').
predicted_stress('F133','Medium').
predicted_stress('F134','Medium').
predicted_stress('F135','Medium').
predicted_stress('F136','Medium').
predicted_stress('F137','Medium').
predicted_stress('F138','Medium').
predicted_stress('F139','Low').
predicted_stress('F140','Low').
predicted_stress('F141','Medium').
predicted_stress('F142','Medium').
predicted_stress('F143','Low').
predicted_stress('F144','Medium').
predicted_stress('F145','Low').
predicted_stress('F146','Medium').
predicted_stress('F147','Medium').
predicted_stress('F148','Medium').
predicted_stress('F149','Medium').
predicted_stress('F150','Medium').
predicted_stress('F151','Medium').
predicted_stress('F152','Medium').
predicted_stress('F153','Medium').
predicted_stress('F154','Low').
predicted_stress('F155','Medium').
predicted_stress('F156','Medium').
predicted_stress('F157','High').
predicted_stress('F158','Medium').
predicted_stress('F159','Low').
predicted_stress('F160','Medium').
predicted_stress('F161','Low').
predicted_stress('F162','Medium').
predicted_stress('F163','Medium').
predicted_stress('F164','Medium').
predicted_stress('F165','Medium').
predicted_stress('F166','Low').
predicted_stress('F167','Medium').
predicted_stress('F168','Medium').
predicted_stress('F169','Medium').
predicted_stress('F170','Medium').
predicted_stress('F171','Low').
predicted_stress('F172','Medium').
predicted_stress('F173','Medium').
predicted_stress('F174','Medium').
predicted_stress('F175','Medium').
predicted_stress('F176','Medium').
predicted_stress('F177','Low').
predicted_stress('F178','Medium').
predicted_stress('F179','Medium').
predicted_stress('F180','Low').
predicted_stress('F181','Medium').
predicted_stress('F182','Medium').
predicted_stress('F183','High').
predicted_stress('F184','Low').
predicted_stress('F185','Medium').
predicted_stress('F186','Medium').
predicted_stress('F187','Medium').
predicted_stress('F188','Medium').
predicted_stress('F189','Medium').
predicted_stress('F190','Medium').
predicted_stress('F191','Medium').
predicted_stress('F192','Medium').
predicted_stress('F193','Medium').
predicted_stress('F194','Medium').
predicted_stress('F195','Low').
predicted_stress('F196','Low').
predicted_stress('F197','Medium').
predicted_stress('F198','Medium').
predicted_stress('F199','Medium').
predicted_stress('F200','Low').
predicted_stress('F201','Medium').
predicted_stress('F202','Medium').
predicted_stress('F203','Medium').
predicted_stress('F204','Low').
predicted_stress('F205','Medium').
predicted_stress('F206','Low').
predicted_stress('F207','Medium').
predicted_stress('F208','Medium').
predicted_stress('F209','Low').
predicted_stress('F210','Medium').
predicted_stress('F211','Low').
predicted_stress('F212','Medium').
predicted_stress('F213','Medium').
predicted_stress('F214','Medium').
predicted_stress('F215','Medium').
predicted_stress('F216','Medium').
predicted_stress('F217','Medium').
predicted_stress('F218','Low').
predicted_stress('F219','Low').
predicted_stress('F220','Medium').
predicted_stress('F221','Low').
predicted_stress('F222','Medium').
predicted_stress('F223','Medium').
predicted_stress('F224','Medium').
predicted_stress('F225','Medium').
predicted_stress('F226','Medium').
predicted_stress('F227','Medium').
predicted_stress('F228','Medium').
predicted_stress('F229','Medium').
predicted_stress('F230','Medium').
predicted_stress('F231','Low').
predicted_stress('F232','Low').
predicted_stress('F233','Medium').
predicted_stress('F234','Low').
predicted_stress('F235','Medium').
predicted_stress('F236','Low').
predicted_stress('F237','Low').
predicted_stress('F238','Medium').
predicted_stress('F239','Medium').
predicted_stress('F240','Medium').
predicted_stress('F241','Medium').
predicted_stress('F242','Low').
predicted_stress('F243','Medium').
predicted_stress('F244','Low').
predicted_stress('F245','Low').
predicted_stress('F246','Medium').
predicted_stress('F247','Medium').
predicted_stress('F248','Medium').
predicted_stress('F249','Low').
predicted_stress('F250','Medium').
